ISI_TOP=	../../..


MAN=
SUBDIR=		linmap_mod repstate_mod flip_mapping domain_mark snap_revert changelist_mod cpstate_mod lin_list_mod compliance_map_mod
SUBDIR_PARALLEL=

.include "${ISI_TOP}/isi.prog.mk"
