/*
 * Copyright (c) 2011
 *	Isilon Systems, LLC.  All rights reserved.
 *
 *	ostore_error.c __ 2011/08/31 12:07:50 PDT __ jonathan
 */
/**
 * @addtogroup ostore_private
 * @{
 */
/** @file
 * Special errors for ostore.
 */

#include "ostore_internal.h"


#define ISI_ERROR_PROTECTED
#include <isi_util/isi_error_protected.h>

/*
 * generic error
 */
ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_error, OSTORE_ERROR_CLASS, ISI_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_error, OSTORE_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_invalid_argument_error, 
    OSTORE_INVALID_ARGUMENT_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_invalid_argument_error, 
    OSTORE_INVALID_ARGUMENT_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_object_not_found_error, 
    OSTORE_OBJECT_NOT_FOUND_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_object_not_found_error, 
    OSTORE_OBJECT_NOT_FOUND_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_attribute_not_found_error, 
    OSTORE_ATTRIBUTE_NOT_FOUND_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_attribute_not_found_error, 
    OSTORE_ATTRIBUTE_NOT_FOUND_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_store_not_mounted, 
    OSTORE_STORE_NOT_MOUNTED_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_store_not_mounted_error, 
    OSTORE_STORE_NOT_MOUNTED_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_invalid_handle, 
    OSTORE_INVALID_HANDLE_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_invalid_handle_error, 
    OSTORE_INVALID_HANDLE_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_access_denied, 
    OSTORE_ACCESS_DENIED_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_access_denied_error, 
    OSTORE_ACCESS_DENIED_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_bucket_exists,
    OSTORE_BUCKET_EXISTS_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_bucket_exists_error, 
OSTORE_BUCKET_EXISTS_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_object_exists,
    OSTORE_OBJECT_EXISTS_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_object_exists_error, 
OSTORE_OBJECT_EXISTS_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_out_of_range,
    OSTORE_OUT_OF_RANGE_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_out_of_range_error, 
    OSTORE_OUT_OF_RANGE_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_exceeds_limit,
    OSTORE_EXCEEDS_LIMIT_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_exceeds_limit_error, 
    OSTORE_EXCEEDS_LIMIT_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_invalid_license,
    OSTORE_INVALID_LICENSE_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_invalid_license_error, 
    OSTORE_INVALID_LICENSE_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_unsupported_object_type,
    OSTORE_UNSUPPORTED_OBJECT_TYPE_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_unsupported_object_type_error,
    OSTORE_UNSUPPORTED_OBJECT_TYPE_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_pathname_not_exist,
    OSTORE_PATHNAME_NOT_EXIST_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_pathname_not_exist_error,
    OSTORE_PATHNAME_NOT_EXIST_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_pathname_not_dir,
    OSTORE_PATHNAME_NOT_DIR_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_pathname_not_dir_error,
    OSTORE_PATHNAME_NOT_DIR_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_pathname_not_onefs,
    OSTORE_PATHNAME_NOT_ONEFS_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_pathname_not_onefs_error,
    OSTORE_PATHNAME_NOT_ONEFS_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_pathname_prohibited,
    OSTORE_PATHNAME_PROHIBITED_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_pathname_prohibited_error,
    OSTORE_PATHNAME_PROHIBITED_ERROR);

ISI_ERROR_CLASS_DEFINE_EMPTY(ostore_copy_to_sub_dir,
    OSTORE_COPY_TO_SUB_DIR_ERROR_CLASS, OSTORE_ERROR_CLASS);
ISI_ERROR_MAKE_NEW_NOARGS(ostore_copy_to_sub_dir_error,
    OSTORE_COPY_TO_SUB_DIR_ERROR);

/** @} */
